CREATE DATABASE UNDB_BANHEIROS;
USE UNDB_BANHEIROS;
CREATE TABLE BANHEIROS(
    IDWC INT IDENTITY PRIMARY KEY, -- ID do banheiro
    NOMEBANHEIRO VARCHAR(100) -- Nome do banheiro
);

CREATE TABLE RESPOSTAS (
    IDRESPOSTA INT IDENTITY PRIMARY KEY, -- ID da resposta
    HRINICIO VARCHAR(25) NOT NULL, -- Inicio
    HRFIM VARCHAR(25) NOT NULL, -- Fim
    WCLIMPO CHAR(3) NOT NULL, -- Banheiro está limpo?
    WCINSUMO CHAR(3) NOT NULL, -- Insumo faltando?
	WCEQUIPDANIFICADO CHAR(3) NOT NULL, -- Equipamento danificado?
    WCINSUMODESCRICAO VARCHAR(255), -- Qual insumo esta faltando?
    WCEQUIPDANIFICADODESCRICAO VARCHAR(255), -- Qual equipamento esta danificado?
	WCNOTA TINYINT NOT NULL, -- Indice de insatisfatório
	CODBANHEIRO INT NOT NULL,
    FOREIGN KEY (CODBANHEIRO) REFERENCES BANHEIROS(IDWC) -- Chave estrangeira
);